config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'
  get 'profiles/update'
  devise_for :users
  root to: "pages#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tools do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings

  get "my_tools", to: "tools#my_tools", as: :my_tools
  get "mon_compte", to: "profiles#mon_compte", as: :mon_compte

  resources :categories, only: [:index]


  end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :tools_categories, dependent: :destroy
  has_many :categories, through: :tools_categories


  has_many :bookings, dependent: :destroy


  validates :name, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :price_per_day, numericality: { greater_than_or_equal_to: 0 }

  has_one_attached :image

  accepts_nested_attributes_for :tools_categories
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  def my_tools
    @tools = current_user.tools
  end

  def index
    if params[:name].present? && params[:city].present?
      @tools = Tool.where("name ILIKE ? AND city ILIKE ?", "#{params[:name]}%", "#{params[:city]}%")
    elsif params[:name].present?
      @tools = Tool.where("name ILIKE ?", "#{params[:name]}%")
    elsif params[:city].present?
      @tools = Tool.where("city ILIKE ?", "#{params[:city]}%")
    else
      @tools = Tool.all
    end
  end

  def new
    @tool = Tool.new
  end

  def show
    @booking = Booking.new
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user



    if @tool.save
      redirect_to tools_path, notice: "L'annonce a été créée avec succès."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tool.update(tool_params)
      redirect_to @tool, notice: "L'annonce a été mise à jour avec succès."
    else
      render :edit
    end
  end

  def destroy
    @tool.destroy
    redirect_to tools_path, notice: "L'annonce a été supprimée avec succès."
  end

  private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :description, :city, :price_per_day, :image, category_ids: [])
  end
end

app/views/tools/edit.html.erb
<div class="container">
  <h1>Modifier l'annonce</h1>
  <%= form_with(model: @tool, local: true) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="actions">
      <%= form.submit 'Enregistrer' %>
      <%= link_to "Supprimer cette annonce", @tool, method: :delete, class: "btn btn-outline-danger btn-sm", data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette annonce ?" } %>
    </div>
  <% end %>
</div>

app/views/tools/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/1249611/pexels-photo-1249611.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1); background-position: center; background-size: cover;">
        <div class="container text-center text-white py-5">
          <h1 class="my-4" style="font-family: 'Montserrat', sans-serif; font-weight: bold; font-size: 3rem;">Liste des annonces</h1>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-md-12 mb-4">
          <form action="/tools" method="get">
            <div class="form-group">
              <label for="category">Filtrer par catégorie:</label>
              <select name="category" id="category" class="form-control">
                <option value="">Toutes les catégories</option>
                <% Category.all.each do |category| %>
                  <option value="<%= category.id %>" <%= 'selected' if params[:category] == category.id.to_s %>> <%= category.name %></option>
                <% end %>
              </select>
            </div>
            <div class="form-group">
              <label for="city">Filtrer par ville:</label>
              <select name="city" id="city" class="form-control">
                <option value="">Toutes les villes</option>
                <% Tool.all.each do |tool| %>
                  <option value="<%= tool.city %>" <%= 'selected' if params[:city] == tool.city.to_s %>> <%= tool.city %></option>
                <% end %>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Filtrer</button>
          </form>
        </div>

        <% @tools.each do |tool| %>
          <% if params[:category].blank? || tool.categories.exists?(id: params[:category]) %>
            <% if params[:city].blank? || tool.city == params[:city] %>
              <div class="col-md-4 mb-4">
                <div class="card">
                  <%= link_to tool_path(tool) do %>
                    <%= cl_image_tag tool.image.key, height: 300, width: 400, crop: :fill, class: "card-img-top" if tool.image.key.present? %>
                  <% end %>
                  <div class="card-body">
                    <h5 class="card-title"><%= tool.name %></h5>
                    <p class="card-text"><i class="fas fa-info-circle"></i> <%= tool.description %></p>
                    <p class="card-text"><i class="fas fa-city"></i> <%= tool.city %></p>
                    <p class="card-text"><i class="fas fa-tags"></i>
                      <% tool.categories.each do |category| %>
                        <%= category.name %>
                        <% unless category == tool.categories.last %>, <% end %>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tools/my_tools.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/1249611/pexels-photo-1249611.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1); background-position: center; background-size: cover;">
        <div class="container text-center text-white py-5">
          <h1 class="my-4" style="font-family: 'Montserrat', sans-serif; font-weight: bold; font-size: 3rem;">Liste des annonces</h1>
        </div>
      </div>

      <div class="row mt-4">
        <% @tools.each do |tool| %>
          <div class="col-md-4 mb-4">
            <div class="card h-100"> <!-- Ajoutez la classe h-100 pour rendre la carte de hauteur égale -->
              <%= link_to tool_path(tool) do %>
                <%= cl_image_tag tool.image.key, height: 300, width: 400, crop: :fill, class: "card-img-top" if tool.image.key.present? %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= tool.name %></h5>
                <p class="card-text"><i class="fa-solid fa-city"></i> <%= tool.city %></p>
                <p class="card-text">
                  <i class="fa-solid fa-list"></i> <!-- Icône pour représenter les catégories -->
                  <% tool.categories.each do |category| %>
                    <%= category.name %>
                    <% unless category == tool.categories.last %>, <% end %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tools/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card" style="box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);">
        <div class="card-body" style="padding: 20px; background-color: #e0e0e0; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
          <h1 class="card-title text-center mb-4" style="font-family: 'Roboto', sans-serif;">Ajouter une nouvelle annonce</h1>

          <%= simple_form_for @tool, html: { multipart: true } do |form| %>
            <div class="form-group mb-3" style="padding: 10px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); margin-bottom: 15px;">
              <%= form.input :name, label: "Nom", class: 'form-control', style: 'border: none; font-family: "Roboto", sans-serif;' %>
            </div>

            <div class="form-group mb-3" style="padding: 10px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); margin-bottom: 15px;">
              <%= form.input :description, as: :text, label: "Description", class: 'form-control', input_html: { rows: 3 }, style: 'border: none; font-family: "Roboto", sans-serif;' %>
            </div>

            <div class="form-group mb-3" style="padding: 10px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); margin-bottom: 15px;">
              <%= form.input :city, label: "Ville", class: 'form-control', style: 'border: none; font-family: "Roboto", sans-serif;' %>
            </div>
             <div class="field">
              <%= form.label :price_per_day %>
              <%= form.number_field :price_per_day %> euros
              </div>

            <div class="form-group mb-3" style="padding: 10px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); margin-bottom: 15px;">
              <%= form.label :image, "Image", class: 'form-label' %>
              <%= form.file_field :image, class: 'form-control-file' %>
            </div>

            <div class="form-group mb-3 text-center" style="padding: 10px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); margin-bottom: 15px;">
              <%= form.label :category_ids, "Sélectionner une ou plusieurs catégories", class: 'form-label' %>
              <div class="d-flex justify-content-center">
                <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                  <div class="form-check">
                    <%= cb.check_box %>
                    <%= cb.label %>
                  </div>
                <% end %>
              </div>
            </div>

            <div class="form-group mb-3 text-center">
              <%= form.button :submit, "Créer l'annonce", class: 'btn btn-primary btn-lg custom-button', style: 'background: #F1B60D; color: black; font-family: "Roboto", sans-serif; width: 100%; border: none;' %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/show.html.erb
<div class="container-fluid min-vh-100 " style="display: flex; align-items: center; justify-content: space-around;">
  <div class="row">
    <div class="col">
      <div class="row mt-4 justify-content-center">
        <div class="col-md-8 mb-4">
          <div class="card" id="card">
            <div class="row no-gutters">
              <% if @tool.image.key.present? %>
                <div class="col-md-4">
                  <%= cl_image_tag @tool.image.key, class: 'card-img' %>
                  <div class="mt-3">
                    <p><i class="fas fa-info-circle"></i> <%= @tool.description %></p>
                    <p><i class="fas fa-city"></i> <%= @tool.city %></p>
                  </div>
                </div>
              <% end %>
              <div class="col-md-8">
                <div class="card-body">
                  <h1 class="mb-4"><%= action_name == 'new' ? 'Créer une Nouvelle Location' : @tool.name %></h1>
                <%= form_for [@tool, @booking], html: { class: "needs-validation", novalidate: true } do |form| %>
                    <div class="mb-3">
                      <%= form.label :start_date, 'Date de début', class: "form-label" %>
                      <%= form.date_field :start_date, class: "form-control", required: true %>
                      <div class="invalid-feedback">
                          Veuillez entrer la date de début de location.
                      </div>
                    </div>
                    <div class="mb-3">
                      <%= form.label :end_date, 'Date de fin', class: "form-label" %>
                      <%= form.date_field :end_date, class: "form-control", required: true %>
                      <div class="invalid-feedback">
                          Veuillez entrer la date de fin de location.
                      </div>
                    </div>
                      <p>
                        <strong>Prix par jour:</strong>
                        <%= @tool.price_per_day %> €
                      </p>
                    <%= form.submit action_name == 'new' ? 'Créer Location' : 'Louer', class: "btn btn-warning" %>
                  <% end %>
                  <%= link_to 'Retour', tools_path, class: "btn btn-secondary mt-3" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>