config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'
  get 'profiles/update'
  devise_for :users
  root to: "pages#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tools do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings

  get "my_tools", to: "tools#my_tools", as: :my_tools
  get "mon_compte", to: "profiles#mon_compte", as: :mon_compte

  resources :categories, only: [:index]


  end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def mon_compte
    @user = current_user
    @tools = current_user.tools
    @bookings = current_user.bookings
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_profile_path, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/profiles/_mes-outils-en-loc.html.erb
<div class="container d-flex">
  <table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nom</th>
      <th scope="col">Date d'ajout</th>
      <th scope="col">État</th>
      <th scope="col"> Loueur </th>
    </tr>
  </thead>
  <tbody>
    <% @user.tools.each do |tool|%>
    <tr>
      <% counter = 0 %>
      <th scope="row"><%= counter += 1 %></th>
      <td><%= tool.name %></td>
      <td><%= tool.created_at.strftime("%d/%m/%Y") %></td>
      <% if tool.bookings.empty? %>
        <td>Disponible</td>
      <% else %>
        <td>Indisponible</td>
        <% end %>
      <% tool.bookings.each do |booking| %>
        <td><%= booking.user.email %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>

app/views/profiles/_mon-profil.html.erb
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
  <div class="card p-4">
    <div class="image d-flex flex-column justify-content-center align-items-center">

        <%= cl_image_tag current_user.image.key, height: 100, width: 100, style: "border-radius: 50px;" %>

      <span class="idd"><%= @user.email %></span>
      <div class="d-flex flex-row justify-content-center align-items-center mt-3">
        <span class="number"><%= @user.tools.count %> <span class="follow"> <%= @user.tools.count > 1 ? "Locations" : "Location" %> </span></span>
      </div>
      <div class="px-2 rounded mt-4 date">
        <span class="join">Joined <%= @user.created_at.strftime("%B, %Y") %></span>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_outils-que-je-loue.html.erb
<% @user.bookings.each do |loc| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= loc.tool.name %></h5>
      <p class="card-text">Durée de ma location : <%= loc.start_date %> au <%= loc.end_date %></p>
      <a href="<%= booking_path(loc) %>" class="btn btn-primary">Voir la location</a>
    </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="containe">
<h1>Editer Profil</h1>

<%= form_with(model: @user, url: profile_path, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pseudo %>
    <%= form.text_field :pseudo, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :mot_de_passe %>
    <%= form.password_field :mot_de_passe, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :mot_de_passe_confirmation %>
    <%= form.password_field :mot_de_passe_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Mettre à jour', class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'retour', root_path, class: "btn btn-secondary" %>
</div>

app/views/profiles/mon_compte.html.erb
<div class="page-container">

  <div class="top" style="display: flex; align-items: center; justify-content: space-around; padding: 40px;">
    <div class="profile-container">
      <%= render 'mon-profil' %>
    </div>
    <div class="my-tools">
      <%= render 'mes-outils-en-loc' %>
    </div>
  </div>

  <div class="2/3 container" style="padding: 40px;">

    <div class="je-loue">
      <div><h3>Outils que je loue</h3></div>
      <%= render 'outils-que-je-loue'%>
    </div>
  </div>

</div>