config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'
  get 'profiles/update'
  devise_for :users
  root to: "pages#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tools do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings

  get "my_tools", to: "tools#my_tools", as: :my_tools
  get "mon_compte", to: "profiles#mon_compte", as: :mon_compte

  resources :categories, only: [:index]


  end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool

  has_one_attached :image

  validates :start_date, :end_date, presence: true
  before_save :calculate_total_price

  private

  def calculate_total_price
    self.total_price = (end_date - start_date).to_i * tool.price_per_day
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  # def new
  #   @booking = Booking.new
  # end

  def edit
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.tool = Tool.find(params[:tool_id])
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: 'Location créée avec succès.'
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Location mise à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Location supprimée avec succès.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :tool_id, :user_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/views/bookings/index.html.erb
<div class="container-fluid my-4">
  <h1 class="text-center mb-4">Mes Locations</h1>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    <% @bookings.each do |booking| %>
      <div class="col">
        <div class="card h-100 shadow">
          <% if booking.tool.image.attached? %>
            <%= cl_image_tag booking.tool.image.key, height: 300, width: 400, crop: :fill, class: "card-img-top" %>
          <% else %>
            <%= image_tag "placeholder_image.jpg", height: 300, width: 400, class: "card-img-top" %>
            <!-- Remplacez "placeholder_image.jpg" par l'URL ou le chemin de votre image de remplacement -->
          <% end %>
          <div class="card-body">
            <h5 class="card-title mb-2"><%= booking.tool.name %></h5>
            <p class="card-text mb-1">Du <%= booking.start_date %> au <%= booking.end_date %></p>
            <p><strong>Prix total :</strong> <%= booking.total_price %> €</p>
            <div class="d-grid gap-2">
              <%#= link_to 'Voir', booking, class: 'btn btn-primary btn-sm' %>
              <%#= link_to 'Éditer', edit_booking_path(booking), class: 'btn btn-warning btn-sm' %>
              <%#= link_to 'Supprimer', booking, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: 'btn btn-danger btn-sm' %>
            </div>
          </div>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container-fluid min-vh-100 my-5">
  <h1 class="mb-4"><%= action_name == 'new' ? 'Créer une Nouvelle Location' : 'Éditer une Location' %></h1>
  <%= form_with(model: @booking, local: true, class: "needs-validation", novalidate: true) do |form| %>
    <div class="mb-3">
      <%= form.label :name, 'Nom de l’outil', class: "form-label" %>
      <%= form.text_field :name, class: "form-control", required: true %>
      <div class="invalid-feedback">
        Veuillez entrer le nom de l’outil.
      </div>
    </div>

    <div class="mb-3">
      <%= form.label :date, 'Date de Location', class: "form-label" %>
      <%= form.date_field :date, class: "form-control", required: true %>
      <div class="invalid-feedback">
        Veuillez entrer la date de location.
      </div>
    </div>

    <%= form.submit action_name == 'new' ? 'Créer Location' : 'Mettre à jour la Location', class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Retour', bookings_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/bookings/show.html.erb
<div class="container-fluid min-vh-100">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <h1>Détails de la Location</h1>
          <p><strong>Nom de l’outil :</strong> <%= @booking.tool.name %></p>
          <p><strong>Date de Location :</strong> <%= @booking.start_date %> au <%= @booking.end_date %></p>

          <%= link_to 'Éditer', edit_booking_path(@booking) %>
          <%= link_to 'Retour', bookings_path %>
        </div>
      </div>
    </div>
  </div>
</div>