config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'
  get 'profiles/update'
  devise_for :users
  root to: "pages#home"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  resources :tools do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings

  get "my_tools", to: "tools#my_tools", as: :my_tools
  get "mon_compte", to: "profiles#mon_compte", as: :mon_compte

  resources :categories, only: [:index]


  end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="text-center">
      <%= link_to(root_path) do %>
        <%= image_tag("logo.png", alt: "Logo", class: "logo") %>
      <% end %>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-6 footer-categories d-flex flex-row">

        <a href="#" style="margin-right: 20px;">Mes locations</a>
        <a href="#" style="margin-right: 20px;">Mes annonces</a>
        <a href="#" style="margin-right: 20px;">Mon compte</a>
        

        <div class="dropdown">
          <button class="btn dropdown-toggle text-white" type="button" id="categoryDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Catégories
          </button>
          <div class="dropdown-menu" aria-labelledby="categoryDropdown">
            <a class="dropdown-item" href="#">Jardinage</a>
            <a class="dropdown-item" href="#">Nettoyage</a>
            <a class="dropdown-item" href="#">Bricolage</a>
            <a class="dropdown-item" href="#">Véhicule</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar" class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container-fluid container">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag("logo.png", alt: "Logo", class: "avatar navbar-link", style: "width: 100px; height: 53px; object-fit: cover;") %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item mx-2">
          </li>
          <li class="nav-item mx-2">
          </li>
          <li class="nav-item mx-2 navbar-link cta-btn">
            <%= link_to 'Déposer une nouvelle annonce', new_tool_path %>
          </li>
          <li class="nav-item navbar-link mx-2">
            <%= link_to 'Voir toutes les annonces', tools_path %>
          </li>
          <li class="nav-item dropdown mx-2">
            <% if current_user %>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= cl_image_tag current_user.image.key, height: 50, width: 50, style: "border-radius: 50px;", crop: :fill %>
              </a>
                <div class="dropdown-menu dropdown-menu-end border-top-none" aria-labelledby="navbarDropdownAccount">
                <%= link_to 'Mes annonces', my_tools_path, class: 'dropdown-item' %>
                <%= link_to 'Mes Locations', bookings_path, class: 'dropdown-item' %>
                <%= link_to 'Mon compte', mon_compte_path,class: 'dropdown-item' %>
                <div class="dropdown-divider"></div>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item", data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
              </div>
            <% else %>
              <%= link_to 'Rechercher un outil', tools_path, class: 'nav-link' %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item mx-2">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>